"""Add pincode to Zone and ConsumerProfile

Revision ID: 0285cb94c6f8
Revises: 60952486e3c1
Create Date: 2026-04-22 23:04:11.258577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0285cb94c6f8'
down_revision = '60952486e3c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consumer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=True))

    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_zones_pincode'), ['pincode'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_pincode'))
        batch_op.drop_column('pincode')

    with op.batch_alter_table('consumer_profiles', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###
