"""Added Pricing History and Outbox Retry

Revision ID: 2501263bb561
Revises: 7c7e1eb17624
Create Date: 2026-04-22 22:33:44.689150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2501263bb561'
down_revision = '7c7e1eb17624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('pricing_tiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricing_tiers', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('effective_date')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
