"""Add consumption models

Revision ID: 3e42e6c5fd32
Revises: 78fbc32b362f
Create Date: 2026-04-21 16:10:07.832289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e42e6c5fd32'
down_revision = '78fbc32b362f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumption_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_kwh', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'date', name='_meter_date_uc')
    )
    with op.batch_alter_table('consumption_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consumption_summary_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_consumption_summary_meter_id'), ['meter_id'], unique=False)

    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('kwh_consumed', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id', 'timestamp', name='_meter_timestamp_uc')
    )
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meter_readings_meter_id'), ['meter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meter_readings_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meter_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meter_readings_timestamp'))
        batch_op.drop_index(batch_op.f('ix_meter_readings_meter_id'))

    op.drop_table('meter_readings')
    with op.batch_alter_table('consumption_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumption_summary_meter_id'))
        batch_op.drop_index(batch_op.f('ix_consumption_summary_date'))

    op.drop_table('consumption_summary')
    # ### end Alembic commands ###
