"""Add baseline_kwh to DREvent

Revision ID: 60952486e3c1
Revises: 2501263bb561
Create Date: 2026-04-22 22:35:12.069772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60952486e3c1'
down_revision = '2501263bb561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_response_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_kwh', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_response_events', schema=None) as batch_op:
        batch_op.drop_column('baseline_kwh')

    # ### end Alembic commands ###
