"""Add UniqueConstraint zone_id event_start on DREvent

Revision ID: 955adb79257e
Revises: 0285cb94c6f8
Create Date: 2026-04-22 23:13:58.958138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955adb79257e'
down_revision = '0285cb94c6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_response_events', schema=None) as batch_op:
        batch_op.create_unique_constraint('_zone_event_start_uc', ['zone_id', 'event_start'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_response_events', schema=None) as batch_op:
        batch_op.drop_constraint('_zone_event_start_uc', type_='unique')

    # ### end Alembic commands ###
